### ISSUE TITLE
Downloadlinks funktionieren nicht

### ISSUE THREAD

**Issue by King-at-Ralph** [rogergerecke/lottogeometry#17]
Hallo Herr Gerecke

Ihre Downloadlinks Lotto Archiv funktionieren nicht

Ich interessiere mich für alle Daten für 6 aus 49 Mittwochs

Danke, Ralph

[lotto-down.zip](https://github.com/rogergerecke/lottogeometry/files/5682953/lotto-down.zip)

**Comment by rogergerecke** [comment]
Ohh ich war schon lange nicht mehr online und habe an meine app nicht mehr gearbeitet

**Comment by rogergerecke** [comment]
[lottodb.zip](https://github.com/rogergerecke/lottogeometry/files/5772736/lottodb.zip)

Ich habe mal die datenbank exportiert

**Comment by King-at-Ralph** [comment]
Danke für die Daten.
nur zur Info: 2018er Daten fehlen komplett.
Danke für Ihre Hilfe.
